/**
 * Generated by API Builder - https://www.apibuilder.io
 * Service version: 0.2.1
 * apibuilder:0.12.52 https://app.apibuilder.io/hbc/echo-api/0.2.1/http4s_0_15
 */
package com.hbccommon.echoApi.api.v0 {
  /**
   * The echo
   * @param message Something to be echoed....
   */
  case class echo(
    message: String
  )

}

package com.hbccommon.echoApi.api.v0 {

  package object json {
    import io.circe.syntax._
    import io.circe.{Decoder, Encoder, Json}

    import scala.util.Try

    // Make Scala 2.11 Either monadic
    private[v0] implicit def eitherOps[A,B](e: Either[A,B]) = cats.implicits.catsSyntaxEither(e)

    private[v0] implicit val decodeUUID: Decoder[_root_.java.util.UUID] =
      Decoder.decodeString.emapTry(str => Try(_root_.java.util.UUID.fromString(str)))

    private[v0] implicit val encodeUUID: Encoder[_root_.java.util.UUID] =
      Encoder.encodeString.contramap[_root_.java.util.UUID](_.toString)

    private[v0] implicit val decodeInstant: Decoder[_root_.java.time.Instant] =
      Decoder.decodeString.emapTry(str => Try(_root_.java.time.Instant.parse(str)))

    private[v0] implicit val encodeInstant: Encoder[_root_.java.time.Instant] =
      Encoder.encodeString.contramap[_root_.java.time.Instant](_.toString)

    private[v0] implicit val decodeLocalDate: Decoder[_root_.java.time.LocalDate] =
      Decoder.decodeString.emapTry(str => Try(_root_.java.time.LocalDate.parse(str)))

    private[v0] implicit val encodeLocalDate: Encoder[_root_.java.time.LocalDate] =
      Encoder.encodeString.contramap[_root_.java.time.LocalDate](_.toString)

    implicit def decodeEchoApiEcho: Decoder[echo] = Decoder.instance { c =>
     for {
        message <- c.downField("message").as[String]
      } yield {
        echo(
          message = message
        )
      }
    }

    implicit def encodeEchoApiEcho: Encoder[echo] = Encoder.instance { t =>
      Json.fromFields(Seq(
        Some("message" -> t.message.asJson)
      ).flatten)
    }
  }
}