platform: linux

inputs:
- name: echo-api-repo

outputs:
- name: artifacts

caches:
- path: echo-api-repo/ivy

params:
  SBT_OPTS: -Dsbt.ivy.home=./ivy

run:
  dir: echo-api-repo
  path: sh
  args:
  - -exc
  - |
    sbt docker:publishLocal
    cp target/docker/stage/*      ../artifacts
    git rev-parse --short HEAD > ../artifacts/commit_sha

